pipeline:
  name: build-sample-react-app
  identifier: buildsamplereactapp
  projectIdentifier: ContinuousIntegration
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: anilgithub
        repoName: react-pipeline-sample
        build: <+input>
        sparseCheckout: []
  stages:
    - stage:
        name: Build
        identifier: Build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: install node modules
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: npm install
              - step:
                  type: Run
                  name: build app
                  identifier: build_app
                  spec:
                    shell: Sh
                    command: npm run build
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: <+input>
                    repo: <+input>
                    tags:
                      - latest
                    dockerfile: Dockerfile
